# Generated by Django 4.1.3 on 2023-01-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'hr'), ('unk', 'Неизвестный'), ('emp', 'Сотрудник')], default='unk', max_length=4),
        ),
    ]
