# Generated by Django 4.1.3 on 2023-01-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский')], default='m', max_length=1),
        ),
    ]
