name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: list dir
        run: ls -lah
      - name: docker build image
        run: docker build -t vmonin/django_skypro_petproject:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: check image
        run: docker images
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u vmonin ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push vmonin/django_skypro_petproject:$GITHUB_REF_NAME-$GITHUB_RUN_ID