name: Build and deploy workflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: list dir
        run: ls -lah
      - name: docker build image
        run: docker build -t vmonin/django_skypro_petproject:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: check image
        run: docker images
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push vmonin/django_skypro_petproject:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:  # Пробрасываем параметры
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "deploy/docker-compose.yaml"  # Что мы будем копировать на сервер
          target: "django_skypro_petproject"  # Куда на сервере положить данные
          strip_components: 1  # Префексы deploy/ будут стерты и файлы лягут прямо в django_skypro_petproject
      - name: run docker-compose on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

          script: |
            cd django_skypro_petproject
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d  # флаг -S - пароль со стандартного потока ввода